### ISSUE TITLE
Test failure in module

### ISSUE THREAD

**Issue by gmossessian** [twmht/python-rocksdb#11]
Hi!

Thanks for the development work. I'm attempting to add a feature (which I will PR if I am successful), but after installing rocksdb 5.4.6 on Sierra and compiling your cython wrapper, I am getting a test failure in `TestOptions.test_simple`:

```
>       self.assertEqual(rocksdb.CompressionType.no_compression, opts.compression)
E       AssertionError: u'no_compression' != u'snappy_compression'
E       - no_compression
E       ?  ^
E       + snappy_compression
E       ? + ^^^^
```

From what I can tell, it looks like the default compression type is not set in your wrapper, so must be set in the base library -- indeed this [seems to be the case](https://github.com/facebook/rocksdb/blob/0ee7f040392de849dbc40c0bd20e1b7e681ef658/java/src/main/java/org/rocksdb/MutableColumnFamilyOptionsInterface.java#L142), at least for the java base library? 

I am assuming this is safe to ignore but wanted to bring it to your attention. 

EDIT It looks like it defaults to Snappy if it is supported, otherwise to no compression:

[https://github.com/facebook/rocksdb/blob/master/options/cf_options.h#L182](https://github.com/facebook/rocksdb/blob/master/options/cf_options.h#L182
)
Thank you!

**Comment by twmht** [comment]
@gmossessian 

I think that this error can be ignored.

I will try to fix that.

thanks for your great PR.

**Comment by twmht** [comment]
now it works with `0.6.9`
