### ISSUE TITLE
import rocksdb issuse:  undefined symbol: _ZTIN7rocksdb10ComparatorE

### ISSUE THREAD

**Issue by azhuoinfogs** [twmht/python-rocksdb#15]
1.Collecting python-rocksdb
Requirement already satisfied: setuptools in /home/guosheng/.local/lib/python2.7/site-packages (from python-rocksdb)
Installing collected packages: python-rocksdb
Successfully installed python-rocksdb-0.6.7
2.
guosheng@guosheng:~/code/db_rock/rocksdb/pyrocks_test$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import rocksdb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/rocksdb/__init__.py", line 1, in <module>
    from ._rocksdb import *
ImportError: /usr/local/lib/python2.7/dist-packages/rocksdb/_rocksdb.so: undefined symbol: _ZTIN7rocksdb10ComparatorE
>>>

**Comment by twmht** [comment]
How you built rocksdb?

**Comment by azhuoinfogs** [comment]
your build ways : (the pyrocks_test/ has finished)
mkdir build
cd build 
guosheng@guosheng:~/code/rocksdb/rocksdb/build$ ### **cmake ..**
-- JNI library is disabled
-- Configuring done
-- Generating done
-- Build files have been written to: /home/guosheng/code/rocksdb/rocksdb/build
guosheng@guosheng:~/code/rocksdb/rocksdb/build$ **make** 
[  1%] Built target testutillib
Scanning dependencies of target build_version
[  1%] Building CXX object CMakeFiles/build_version.dir/build_version.cc.o
[  1%] Built target build_version
[  2%] Linking CXX shared library librocksdb.so
[ 31%] Built target rocksdb-shared
[ 31%] Linking CXX executable c_test
[ 31%] Built target c_test
[ 31%] Built target gtest
[ 31%] Built target testharness
[ 31%] Linking CXX executable ttl_test
[ 31%] Built target ttl_test
[ 31%] Linking CXX executable write_prepared_transaction_test
[ 31%] Built target write_prepared_transaction_test
[ 31%] Linking CXX executable transaction_test
[ 31%] Built target transaction_test
[ 31%] Linking CXX executable compact_on_deletion_collector_test
[ 32%] Built target compact_on_deletion_collector_test
[ 33%] Linking CXX executable redis_lists_test
[ 33%] Built target redis_lists_test
[ 33%] Linking CXX executable option_change_migration_test
[ 33%] Built target option_change_migration_test
[ 33%] Linking CXX executable object_registry_test
[ 33%] Built target object_registry_test
[ 33%] Linking CXX executable memory_test
[ 33%] Built target memory_test
[ 33%] Linking CXX executable geodb_test
[ 33%] Built target geodb_test
[ 33%] Linking CXX executable json_document_test
[ 33%] Built target json_document_test
[ 33%] Linking CXX executable document_db_test
[ 33%] Built target document_db_test
[ 33%] Linking CXX executable date_tiered_test
[ 34%] Built target date_tiered_test
[ 34%] Linking CXX executable column_aware_encoding_test
[ 34%] Built target column_aware_encoding_test
[ 34%] Linking CXX executable checkpoint_test
[ 34%] Built target checkpoint_test
[ 34%] Linking CXX executable cassandra_serialize_test
[ 35%] Built target cassandra_serialize_test
[ 35%] Linking CXX executable cassandra_row_merge_test
[ 35%] Built target cassandra_row_merge_test
[ 35%] Linking CXX executable cassandra_functional_test
[ 35%] Built target cassandra_functional_test
[ 36%] Linking CXX executable backupable_db_test
[ 36%] Built target backupable_db_test
[ 36%] Linking CXX executable timer_queue_test
[ 36%] Built target timer_queue_test
[ 36%] Linking CXX executable slice_transform_test
[ 36%] Built target slice_transform_test
[ 36%] Linking CXX executable heap_test
[ 36%] Built target heap_test
[ 36%] Linking CXX executable hash_test
[ 36%] Built target hash_test
[ 36%] Linking CXX executable blob_db_test
[ 36%] Built target blob_db_test
[ 36%] Linking CXX executable filelock_test
[ 36%] Built target filelock_test
[ 37%] Linking CXX executable file_reader_writer_test
[ 37%] Built target file_reader_writer_test
[ 37%] Linking CXX executable event_logger_test
[ 37%] Built target event_logger_test
[ 37%] Linking CXX executable options_util_test
[ 37%] Built target options_util_test
[ 38%] Linking CXX executable crc32c_test
[ 38%] Built target crc32c_test
[ 38%] Linking CXX executable coding_test
[ 38%] Built target coding_test
[ 38%] Linking CXX executable spatial_db_test
[ 38%] Built target spatial_db_test
[ 38%] Linking CXX executable auto_roll_logger_test
[ 38%] Built target auto_roll_logger_test
[ 38%] Linking CXX executable sst_dump_test
[ 39%] Built target sst_dump_test
[ 39%] Linking CXX executable db_test2
[ 39%] Built target db_test2
[ 39%] Linking CXX executable merge_helper_test
[ 39%] Built target merge_helper_test
[ 39%] Linking CXX executable db_test
[ 39%] Built target db_test
[ 39%] Linking CXX executable compact_files_test
[ 39%] Built target compact_files_test
[ 39%] Linking CXX executable prefix_test
[ 39%] Built target prefix_test
[ 40%] Linking CXX executable db_sst_test
[ 40%] Built target db_sst_test
[ 40%] Linking CXX executable db_bloom_filter_test
[ 40%] Built target db_bloom_filter_test
[ 40%] Linking CXX executable thread_list_test
[ 40%] Built target thread_list_test
[ 41%] Linking CXX executable log_test
[ 41%] Built target log_test
[ 41%] Linking CXX executable db_log_iter_test
[ 41%] Built target db_log_iter_test
[ 41%] Linking CXX executable write_batch_with_index_test
[ 41%] Built target write_batch_with_index_test
[ 41%] Linking CXX executable arena_test
[ 41%] Built target arena_test
[ 41%] Linking CXX executable version_set_test
[ 41%] Built target version_set_test
[ 41%] Linking CXX executable db_iter_test
[ 42%] Built target db_iter_test
[ 42%] Linking CXX executable db_inplace_update_test
[ 42%] Built target db_inplace_update_test
[ 42%] Linking CXX executable db_flush_test
[ 42%] Built target db_flush_test
[ 42%] Linking CXX executable db_dynamic_level_test
[ 43%] Built target db_dynamic_level_test
[ 43%] Linking CXX executable env_basic_test
[ 44%] Built target env_basic_test
[ 45%] Linking CXX executable db_memtable_test
[ 45%] Built target db_memtable_test
[ 45%] Linking CXX executable db_compaction_filter_test
[ 45%] Built target db_compaction_filter_test
[ 45%] Linking CXX executable cache_test
[ 46%] Built target cache_test
[ 46%] Linking CXX executable stringappend_test
[ 46%] Built target stringappend_test
[ 46%] Linking CXX executable autovector_test
[ 46%] Built target autovector_test
[ 46%] Linking CXX executable dbformat_test
[ 46%] Built target dbformat_test
[ 46%] Linking CXX executable dynamic_bloom_test
[ 46%] Built target dynamic_bloom_test
[ 47%] Linking CXX executable hash_table_bench
[ 47%] Built target hash_table_bench
[ 47%] Linking CXX static library librocksdb.a
[ 76%] Built target rocksdb
[ 76%] Linking CXX executable plain_table_db_test
[ 77%] Built target plain_table_db_test
[ 77%] Linking CXX executable table_reader_bench
[ 77%] Built target table_reader_bench
[ 77%] Linking CXX executable thread_local_test
[ 78%] Built target thread_local_test
[ 78%] Linking CXX executable compaction_iterator_test
[ 78%] Built target compaction_iterator_test
[ 78%] Linking CXX executable db_table_properties_test
[ 78%] Built target db_table_properties_test
[ 78%] Linking CXX executable compaction_job_stats_test
[ 78%] Built target compaction_job_stats_test
[ 78%] Linking CXX executable cache_bench
[ 78%] Built target cache_bench
[ 79%] Linking CXX executable table_properties_collector_test
[ 79%] Built target table_properties_collector_test
[ 80%] Linking CXX executable db_block_cache_test
[ 80%] Built target db_block_cache_test
[ 80%] Linking CXX executable options_settable_test
[ 80%] Built target options_settable_test
[ 81%] Linking CXX executable column_aware_encoding_exp
[ 81%] Built target column_aware_encoding_exp
[ 81%] Linking CXX executable persistent_cache_test
[ 81%] Built target persistent_cache_test
[ 81%] Linking CXX executable db_basic_test
[ 81%] Built target db_basic_test
[ 81%] Linking CXX executable db_merge_operator_test
[ 81%] Built target db_merge_operator_test
[ 81%] Linking CXX executable db_universal_compaction_test
[ 81%] Built target db_universal_compaction_test
[ 82%] Linking CXX executable delete_scheduler_test
[ 82%] Built target delete_scheduler_test
[ 82%] Linking CXX executable db_range_del_test
[ 83%] Built target db_range_del_test
[ 83%] Linking CXX executable db_properties_test
[ 83%] Built target db_properties_test
[ 83%] Linking CXX executable memtablerep_bench
[ 83%] Built target memtablerep_bench
[ 83%] Linking CXX executable corruption_test
[ 83%] Built target corruption_test
[ 83%] Linking CXX executable cassandra_format_test
[ 83%] Built target cassandra_format_test
[ 83%] Linking CXX executable options_file_test
[ 83%] Built target options_file_test
[ 83%] Linking CXX executable db_options_test
[ 83%] Built target db_options_test
[ 83%] Linking CXX executable ldb_cmd_test
[ 83%] Built target ldb_cmd_test
[ 83%] Linking CXX executable column_family_test
[ 83%] Built target column_family_test
[ 83%] Linking CXX executable rate_limiter_test
[ 83%] Built target rate_limiter_test
[ 83%] Linking CXX executable lru_cache_test
[ 83%] Built target lru_cache_test
[ 83%] Linking CXX executable cuckoo_table_db_test
[ 83%] Built target cuckoo_table_db_test
[ 84%] Linking CXX executable db_tailing_iter_test
[ 84%] Built target db_tailing_iter_test
[ 84%] Linking CXX executable bloom_test
[ 85%] Built target bloom_test
[ 85%] Linking CXX executable db_wal_test
[ 86%] Built target db_wal_test
[ 86%] Linking CXX executable comparator_db_test
[ 86%] Built target comparator_db_test
[ 86%] Linking CXX executable db_write_test
[ 86%] Built target db_write_test
[ 86%] Linking CXX executable db_bench
[ 86%] Built target db_bench
[ 86%] Linking CXX executable compaction_picker_test
[ 86%] Built target compaction_picker_test
[ 86%] Linking CXX executable deletefile_test
[ 86%] Built target deletefile_test
[ 86%] Linking CXX executable external_sst_file_basic_test
[ 86%] Built target external_sst_file_basic_test
[ 86%] Linking CXX executable fault_injection_test
[ 86%] Built target fault_injection_test
[ 86%] Linking CXX executable file_indexer_test
[ 86%] Built target file_indexer_test
[ 86%] Linking CXX executable hash_table_test
[ 86%] Built target hash_table_test
[ 86%] Linking CXX executable filename_test
[ 86%] Built target filename_test
[ 86%] Linking CXX executable external_sst_file_test
[ 87%] Built target external_sst_file_test
[ 88%] Linking CXX executable wal_manager_test
[ 88%] Built target wal_manager_test
[ 88%] Linking CXX executable flush_job_test
[ 88%] Built target flush_job_test
[ 89%] Linking CXX executable compaction_job_test
[ 89%] Built target compaction_job_test
[ 89%] Linking CXX executable db_io_failure_test
[ 89%] Built target db_io_failure_test
[ 89%] Linking CXX executable manual_compaction_test
[ 89%] Built target manual_compaction_test
[ 90%] Linking CXX executable memtable_list_test
[ 90%] Built target memtable_list_test
[ 90%] Linking CXX executable perf_context_test
[ 90%] Built target perf_context_test
[ 90%] Linking CXX executable table_test
[ 90%] Built target table_test
[ 90%] Linking CXX executable repair_test
[ 90%] Built target repair_test
[ 90%] Linking CXX executable version_builder_test
[ 91%] Built target version_builder_test
[ 91%] Linking CXX executable version_edit_test
[ 91%] Built target version_edit_test
[ 91%] Linking CXX executable rocks_lua_test
[ 91%] Built target rocks_lua_test
[ 91%] Linking CXX executable write_batch_test
[ 91%] Built target write_batch_test
[ 91%] Linking CXX executable write_callback_test
[ 92%] Built target write_callback_test
[ 93%] Linking CXX executable optimistic_transaction_test
[ 93%] Built target optimistic_transaction_test
[ 93%] Linking CXX executable env_test
[ 93%] Built target env_test
[ 93%] Linking CXX executable mock_env_test
[ 93%] Built target mock_env_test
[ 93%] Linking CXX executable db_iterator_test
[ 93%] Built target db_iterator_test
[ 93%] Linking CXX executable inlineskiplist_test
[ 93%] Built target inlineskiplist_test
[ 93%] Linking CXX executable skiplist_test
[ 94%] Built target skiplist_test
[ 94%] Linking CXX executable db_compaction_test
[ 94%] Built target db_compaction_test
[ 94%] Linking CXX executable listener_test
[ 94%] Built target listener_test
[ 94%] Linking CXX executable write_buffer_manager_test
[ 94%] Built target write_buffer_manager_test
[ 95%] Linking CXX executable histogram_test
[ 95%] Built target histogram_test
[ 95%] Linking CXX executable cuckoo_table_builder_test
[ 95%] Built target cuckoo_table_builder_test
[ 95%] Linking CXX executable sim_cache_test
[ 95%] Built target sim_cache_test
[ 95%] Linking CXX executable db_statistics_test
[ 95%] Built target db_statistics_test
[ 95%] Linking CXX executable iostats_context_test
[ 95%] Built target iostats_context_test
[ 95%] Linking CXX executable reduce_levels_test
[ 95%] Built target reduce_levels_test
[ 95%] Linking CXX executable statistics_test
[ 95%] Built target statistics_test
[ 95%] Linking CXX executable block_test
[ 95%] Built target block_test
[ 95%] Linking CXX executable options_test
[ 96%] Built target options_test
[ 96%] Linking CXX executable merger_test
[ 97%] Built target merger_test
[ 97%] Linking CXX executable block_based_filter_block_test
[ 97%] Built target block_based_filter_block_test
[ 97%] Linking CXX executable write_controller_test
[ 97%] Built target write_controller_test
[ 97%] Linking CXX executable cuckoo_table_reader_test
[ 97%] Built target cuckoo_table_reader_test
[ 97%] Linking CXX executable merge_test
[ 97%] Built target merge_test
[ 97%] Linking CXX executable full_filter_block_test
[ 98%] Built target full_filter_block_test
[ 99%] Linking CXX executable write_stress
[ 99%] Built target write_stress
[ 99%] Linking CXX executable db_stress
[ 99%] Built target db_stress
[ 99%] Linking CXX executable sst_dump
[ 99%] Built target sst_dump
[ 99%] Linking CXX executable ldb
[100%] Built target ldb
[100%] Linking CXX executable db_repl_stress
[100%] Built target db_repl_stress
[100%] Linking CXX executable db_sanity_test
[100%] Built target db_sanity_test
[100%] Linking CXX executable rocksdb_undump
[100%] Built target rocksdb_undump
[100%] Linking CXX executable rocksdb_dump
[100%] Built target rocksdb_dump
guosheng@guosheng:~/code/rocksdb/rocksdb/build$ e**xport CPLUS_INCLUDE_PATH=${CPLUS_INCLUDE_PATH}:`pwd`/../include
guosheng@guosheng:~/code/rocksdb/rocksdb/build$ export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:`pwd`
guosheng@guosheng:~/code/rocksdb/rocksdb/build$ export LIBRARY_PATH=${LIBRARY_PATH}:`pwd`**
guosheng@guosheng:~/code/rocksdb/rocksdb/build$ source ~/.bashrc
guosheng@guosheng:~/code/rocksdb/rocksdb/build$ cd ../
guosheng@guosheng:~/code/rocksdb/rocksdb$ cd pyrocks_test/
guosheng@guosheng:~/code/rocksdb/rocksdb/pyrocks_test$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import rocksdb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/rocksdb/__init__.py", line 1, in <module>
    from ._rocksdb import *
ImportError: /usr/local/lib/python2.7/dist-packages/rocksdb/_rocksdb.so: undefined symbol: _ZTIN7rocksdb10ComparatorE
>>>

**Comment by twmht** [comment]
Did you use pyenv or other virtualenv?

**Comment by azhuoinfogs** [comment]
i have  installed  python3;
in addition； because i import the rrocksdb  failed,so i try  to  many ways,and install the python-rocksdb many times in different  dir.

**Comment by rimpybharot** [comment]
Facing the same issue.
Working on python 3.6
Steps followed are:
apt-get install build-essential libsnappy-dev zlib1g-dev libbz2-dev libgflags-dev
sudo apt-get install build-essential libsnappy-dev zlib1g-dev libbz2-dev libgflags-dev
git clone https://github.com/facebook/rocksdb.git
cd rocksdb/
mkdir build &&  cd build
cmake ..
make
cd ..
export CPLUS_INCLUDE_PATH=${CPLUS_INCLUDE_PATH}:include
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:build
export LIBRARY_PATH=${LIBRARY_PATH}:build
pip install cython
pip install python-rocksdb
python3.6 -c 'import rocksdb'

Output:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/rocksdb/__init__.py", line 1, in <module>
    from ._rocksdb import *
ImportError: /usr/local/lib/python3.6/dist-packages/rocksdb/_rocksdb.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZTIN7rocksdb10ComparatorE
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/rocksdb/__init__.py", line 1, in <module>
    from ._rocksdb import *
ImportError: /usr/local/lib/python3.6/dist-packages/rocksdb/_rocksdb.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZTIN7rocksdb10ComparatorE

**Comment by twmht** [comment]
Hi guys,

I use pyenv (https://github.com/pyenv/pyenv) to manage the python environment.

And it works without exceptions.

Can you try `pyenv` to install  `python-rocksdb`?

**Comment by twmht** [comment]
the document for installation is updated.

thanks @rimpybharot .

@azhuoinfogs 

do you activate python virtual environment?

**Comment by rimpybharot** [comment]
Yes I used virtualenv for python-rocksdb.

**Comment by schmidtc** [comment]
same problem, was able to get it working by doing make install from the rocksdb build directory.
These are the steps I used:
```
ubuntu:~/src/rocksdb$ mkdir build && cd build
... clipped
ubuntu:~/src/rocksdb/build$ cmake ..
... clipped
ubuntu:~/src/rocksdb/build$ sudo make install-shared INSTALL_PATH=/usr
make: *** No rule to make target 'install-shared'.  Stop.
ubuntu:~/src/rocksdb/build$ cd ..
ubuntu:~/src/rocksdb$ sudo make install-shared INSTALL_PATH=/usr
... This seemed to work, but python-rocksdb still doesn't work ...
ubuntu:~/src/rocksdb$ cd build
ubuntu:~/src/rocksdb/build$ sudo make install
... clipped
```
After the last step I reinstalled python-rocksdb to be safe and everything works.

**Comment by julian05060506** [comment]
thx @schmidtc
i work on python2.7
after your suggest it's work nomal

**Comment by julian05060506** [comment]
thx @schmidtc
i work on python2.7
after your suggest it's work nomal

**Comment by jmliz** [comment]
This worked for me:

```
sudo apt-get install build-essential libsnappy-dev zlib1g-dev libbz2-dev libgflags-dev
git clone https://github.com/facebook/rocksdb.git
cd rocksdb
mkdir build && cd build
cmake ..
make
sudo make install INSTALL_PATH=/usr
```

Install / reinstall python-rocksdb

```
sudo pip3.6 uninstall python-rocksdb
sudo pip3.6 install python-rocksdb

```

**Comment by gcp** [comment]
This is the same problem as #17.

rocksdb in release mode adds -fno-rtti unless you specify USE_RTTI=1 while building, accidentally build in debug mode, or use the CMake build (which is missing this optimization).

But python-rocksdb doesn't add this flag, so things are incompatible.
