### ISSUE TITLE
how to set a merge_operator default?

### ISSUE THREAD

**Issue by young001** [twmht/python-rocksdb#2]
hi,twmht,I read pyrocksdb doc,only one case to set merge_operator AssocCounter,rocks have default mergeOperator,such "uint64add",in java code options.setMergeOperatorName("uint64add");

how to do the same thing in python-rocksdb?

class AssocCounter(rocksdb.interfaces.AssociativeMergeOperator):
    def merge(self, key, existing_value, value):
        if existing_value:
            s = int(existing_value) + int(value)
            return (True, str(s).encode('ascii'))
        return (True, value)

    def name(self):
        return b'AssocCounter'

opts = rocksdb.Options()
opts.create_if_missing = True
opts.merge_operator = AssocCounter()

**Comment by twmht** [comment]
Hi @young001 

So you mean that if you give the name, it will return the default merge operator you want?

**Comment by young001** [comment]
I'm in a case like:
I open a rocksdb using java,because I use the uint64add merge_operator,so I use options.setMergeOperatorName("uint64add"); set rocksdb to use uint64add merge_operator in java,uint64add is a merge_operator supported by rocksdb:https://github.com/facebook/rocksdb/blob/master/utilities/merge_operators.h

when i open the rocksdb created by java using uint64add merge_operator ,python-rocksdb will fail and tell "corruption: Error: Could not perform merge.",so I ask how to open rocksdb dir created by java with a "uint64add" merge_operator using python-rocksdb

**Comment by twmht** [comment]
@young001 

Can you post you code here?

So that I can reproduce the exceptions.

thanks!

**Comment by twmht** [comment]
@young001 

ok, I got it.

this is a bug. I will fix it as soon as possible.

**Comment by young001** [comment]
sorry for a late replay,I just want to give you test code.

**Comment by twmht** [comment]
@young001 

that's ok.

the bug will be fixed as soon as possible.

thank you for reporting the bug.

**Comment by twmht** [comment]
@young001 

I have created `uint64add ` merge operator.

Since the document is not updated yet, I can show you the usage about this operator.

```
import rocksdb
import struct
opts = rocksdb.Options()
opts.create_if_missing = True
opts.merge_operator = 'uint64add'
db = rocksdb.DB("test.db", opts)
# since every operand is uint64, you need to pack it into string
db.put(b'a', struct.pack('Q', 1000))
db.merge(b'a', struct.pack('Q', 2000))

assert struct.unpack('Q', db.get(b'a'))[0] == 3000
```

Please close this issue if this solves your problem:)

**Comment by young001** [comment]
great,thx

**Comment by twmht** [comment]
@young001 

Please see the usage which was updated few days ago.

http://python-rocksdb.readthedocs.io/en/latest/tutorial/index.html#mergeoperator
