### ISSUE TITLE
librocksdb.so.5.13 cannot open shared object file

### ISSUE THREAD

**Issue by davidgallegolobato** [twmht/python-rocksdb#29]
Hi,

After following the instructions it looks like rocksdb cannot be resolved. From Visual Code, when importing rocksdb I get 'Unresolved import rocksb', from the command line, when running python and doing an import I get: 'ImportError: librocksdb.so.5.13: cannot open shared object file: No such file or directory'.

It is happening with and without VirtualEnv.

Any ideas?

Thanks.

Env:
Python 2.7.15rc1.
Ubuntu 18.04.
Rocksdb 5.12.4.

**Comment by twmht** [comment]
I have never tried Visual Code.

But I guess that this issue is related to the configuration of visual code:)
