### ISSUE TITLE
python-rocksdb do not support SeekForPrev api

### ISSUE THREAD

**Issue by young001** [twmht/python-rocksdb#3]
rocksdb support SeekForPrev from 4.13, it's a great feature, it can be a lot easier to do some date-related work, https://github.com/facebook/rocksdb/wiki/SeekForPrev .python-rocksdb need to support it

**Comment by twmht** [comment]
@young001 

It sounds great.

This feature is coming soon.

thanks!

**Comment by young001** [comment]
pls let me know when this feature will be supported :-)

**Comment by twmht** [comment]
@young001 

you can use `SeekForPrev` now.

Please install `python-rocksdb 0.6.5`

Here is the example (http://python-rocksdb.readthedocs.io/en/latest/tutorial/index.html#iteration)

```
db.put(b'a1', b'a1_value')
db.put(b'a3', b'a3_value')
db.put(b'b1', b'b1_value')
db.put(b'b2', b'b2_value')
db.put(b'c2', b'c2_value')
db.put(b'c4', b'c4_value')

it = db.iteritems()
it.seek(b'a1')
assertEqual(it.get(), (b'a1', b'a1_value'))
it.seek(b'a3')
assertEqual(it.get(), (b'a3', b'a3_value'))
it.seek_for_prev(b'c4')
assertEqual(it.get(), (b'c4', b'c4_value'))
it.seek_for_prev(b'c3')
assertEqual(it.get(), (b'c2', b'c2_value'))
```

Please close the issue if you've tested it.

Thanks!

**Comment by young001** [comment]
cool!sorry for late comments,too busy these days
