### ISSUE TITLE
No status codes on simple operations

### ISSUE THREAD

**Issue by klarose** [twmht/python-rocksdb#33]
The rocksdb cpp library returns a Status object for each operation. Unfortunately, operations such as Put or Delete don't seem to return anything when the operation fails. For example, if I do the following:

```
import rocksdb
# Create an entirely new database
db = rocksdb.DB("/tmp/foo", rocksdb.Options(create_if_missing=True))
result = db.delete("blah")
print(result)
```
`result` is None. No exceptions are raised.

This makes it hard to build an API that responds to failures or unexpected events. For example, I may want to take a different path if I try to delete an object which does not exist. Of course, I could try to get it first, and if that fails, then error out, but that's not very efficient.

Would it be possible to extend the API somehow to allow this?

**Comment by fried** [comment]
So looked at all the operations we check the status.   The underlying Rocksdb doesn't consider a delete for a non-existent key to be an error so the status is OK

**Comment by klarose** [comment]
Okay. If it exposes any errors that do occur, I'm fine with it. :) That said, I can't quite figure out how I as a user would use them... How does cython translate them? Is it in the generated .cpp  that seems to have been installed alongside the package? Maybe I can figure it out for myself.

**Comment by klarose** [comment]
Ah, I see.
For example, this function is called if the error is not "not found" for get():
https://github.com/twmht/python-rocksdb/blob/98910c2dce41c02aaa1745ae09e9d5fcdde34bdd/rocksdb/_rocksdb.pyx#L67

And it raises one of the errors there. I guess it's unclear how the state of the DB maps to those. That said, the actual rocksdb documentation doesn't seem to make that clear either. :(

Should we update this issue to ask for a docs update? Or should I just open a new one?

**Comment by twmht** [comment]
Please see the branch `pybind11`. Now every transaction returns the status. And more information are going to update in the document.
