### ISSUE TITLE
illegal instruction

### ISSUE THREAD

**Issue by vinnyvoo** [twmht/python-rocksdb#34]
```
root@vmi210639:/home/rocksdb/pyrocks_test# python3.6 -c 'import rocksdb'
Illegal instruction
```

**Comment by abhiramr** [comment]
@vinnyvoo Unable to replicate your error. Have you followed the instructions on the README completely? 
https://github.com/twmht/python-rocksdb/blob/master/README.rst

**Comment by vinnyvoo** [comment]
the issue was resolved after i rebuild. thanks. closing.
