### ISSUE TITLE
Question: Highest rocksDB version

### ISSUE THREAD

**Issue by iFA88** [twmht/python-rocksdb#37]
Greetings!

I would like to know which is the highest version of rocksDB [ https://github.com/facebook/rocksdb/releases ] are compatible with the python rocksDB lib. I currently use version 5.8 which runs perfectly.

Thanks.

**Comment by twmht** [comment]
Now it supports latest rocksdb.

**Comment by iFA88** [comment]
Hi!

Sadly not anymore. i have error during install the pyrocksdb from pip with the RocksDB v5.18.3:

```
/home/rocksdb/include/rocksdb/filter_policy.h:27:25: fatal error: db/dbformat.h: No such file or directory
     #include "db/dbformat.h"
```

I will try older version.

**Comment by iFA88** [comment]
With v5.17.2 is the same.
