### ISSUE TITLE
Import Error - undefined symbol: _ZN7rocksdb11NewLRUCacheEmibd

### ISSUE THREAD

**Issue by SuBPaR42** [twmht/python-rocksdb#41]
Debian 9 with Python 3.7.2 built from source.  Application I use is suggested to update to python3.7 so trying to get rocksdb (python-rocksdb) working.  In 3.6 was using pyrocksdb without issue.

Subject line describes the error

`ImportError: /usr/local/lib/python3.7/site-packages/rocksdb/_rocksdb.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN7rocksdb11NewLRUCacheEmibd`

**Comment by twmht** [comment]
@SuBPaR42 

Did you use virtualenv or pyenv?

**Comment by SuBPaR42** [comment]
@twmht - I used neither but will try again with your suggestion and probably use virtualenv

**Comment by SuBPaR42** [comment]
Built in virtualenv (manually selected python3.7 with the --python switch) and then also used python3.7 -m pip to do the install from git (have multiple python versions - debian still using python2 and 3.5).

Same error...
