### ISSUE TITLE
rocksdb dealloc error

### ISSUE THREAD

**Issue by iFA88** [twmht/python-rocksdb#45]
Greetings!
With the latest master of `python-rocksdb` and with v5.18.3 of RocksDB I get this error on exit even when I use column families or not:

```
AttributeError: 'list' object has no attribute 'clear'
Exception AttributeError: "'list' object has no attribute 'clear'" in 'rocksdb._rocksdb.DB.__dealloc__' ignored
```

**Comment by twmht** [comment]
@iFA88 

Can you provide the sample code to reproduce this problem?

**Comment by iFA88** [comment]
Its simple, i got this for every deallocation:

```
root@debian:/mnt# python
Python 2.7.13 (default, Sep 26 2018, 18:42:22) 
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import rocksdb
>>> opt = rocksdb.Options(create_if_missing=True)
>>> db = rocksdb.DB("/tmp/test1221", opt)
>>> del db
AttributeError: 'list' object has no attribute 'clear'
Exception AttributeError: "'list' object has no attribute 'clear'" in 'rocksdb._rocksdb.DB.__dealloc__' ignored
>>>
```

**Comment by twmht** [comment]
@iFA88 

Did you try to downgrade the version of rocksdb?

By the way, I am going to release the newer version of rocksdb, which includes a specific version of rocksdb.

**Comment by twmht** [comment]
@iFA88 

I am going to release a newer version of `python-rocksdb` in a few days. It should provide the basic functions. 

for the current version of `python-rocksdb`, I would suggest that you should not manually deallocate the instance.

**Comment by iFA88** [comment]
I think the problem is, that I\m using python 2.7 and `list.clear()` is added in python 3.3.

**Comment by iFA88** [comment]
I recommend to using:
`del list[:]`
