### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by iFA88** [twmht/python-rocksdb#46]
Something went wrong when i delete the db pointer :) For me it is not a critical, because i never close the database without ending my program.

```
(fsPython) root@srv:/own/services/back/src/database/new# python
Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import rocksdb
>>> opt = rocksdb.Options()
>>> db = rocksdb.DB("/tmp/2323", rocksdb.Options(create_if_missing=True))
>>> db.close()
>>> del db
Segmentation fault
(fsPython) root@srv:/own/services/back/src/database/new# 
```

Maybe it is not good when i got this during exit:
```
(fsPython) root@srv:/own/services/back/src/database/new# python
Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import rocksdb
>>> opt = rocksdb.Options()
>>> db = rocksdb.DB("/tmp/2323", rocksdb.Options(create_if_missing=True))
>>> db.close()
>>> exit()
Segmentation fault
(fsPython) root@srv:/own/services/back/src/database/new# 
```

`Linux srv 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64 GNU/Linux`

***Update***

Debug:
https://gist.github.com/iFA88/1e688ea42a2e58d0f8ca88f16657acfa

**Comment by itboyljm** [comment]
hello, could you plz tell me what version of rocksdb you are using? Why there would be close method of Rocksdb DB obj?

**Comment by iFA88** [comment]
Hey, sorry for the long inactivity. It was a very simple bug which has been fixed in my fork. The problem was, that during `__dealloc__` started closing the already closed DB: https://github.com/iFA88/python-rocksdb/blob/master/rocksdb/_rocksdb.pyx#L1723-L1745

**Comment by itboyljm** [comment]
thank you so much for your fast reply. I try your version and it does solve the double free problem. But I still will meet the problem--"No Locks available" if I open, close and reopen, close same db object. Have you ever met this problem when you try to open after close same db?

**Comment by iFA88** [comment]
Yes you have right, I will try to solve this problem.

**Comment by binh-vu** [comment]
I have the same issue when I close and reopen the db again. If I use the `db.close()` function I get segmentation fault. If I only run `del db; gc.collect()` then I get "No Locks available" like @itboyljm.

UPDATE:

I found that @iFA88 created a fork (https://github.com/iFA88/python-rocksdb) that fixed this issue. I put it out here in case anyone encounter the same problem. Thanks @iFA88
