### ISSUE TITLE
AttributeError: module 'pyrocksdb' has no attribute 'DB'

### ISSUE THREAD

**Issue by jefferyanderson** [twmht/python-rocksdb#49]
I've tried the installation 3 times - wiped/cleaned everything related to rocksdb and started from scratch each time, but still have the same result.
This is using the instructions from here, on Ubuntu 18.04.1 LTS:
https://github.com/twmht/python-rocksdb/tree/pybind11

After a successful installation into my Python 3.6.7 virtual environment, I get this when trying to follow through the example:
`
>import pyrocksdb
>db = pyrocksdb.DB()
>Traceback (most recent call last):
>>  File "<stdin>", line 1, in <module>
>>AttributeError: module 'pyrocksdb' has no attribute 'DB'
`

I've also tried installing outside my virtual environment and with python2.7 - issues each time. Any guidance you can provide would be much appreciated.

**Comment by twmht** [comment]
@jefferyanderson 

the fix is coming soon.

**Comment by twmht** [comment]
@jefferyanderson 

I have updated the branch, and it should work now.

**Comment by jefferyanderson** [comment]
Perfect - that fixed it. Thanks for the super fast help!
