### ISSUE TITLE
Compilation fails

### ISSUE THREAD

**Issue by bauerj** [twmht/python-rocksdb#5]
This is using Python 3.6 and RocksDB 5.2.1.

```
    writing dependency_links to python_rocksdb.egg-info/dependency_links.txt
    writing requirements to python_rocksdb.egg-info/requires.txt
    writing top-level names to python_rocksdb.egg-info/top_level.txt
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'python_rocksdb.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'python_rocksdb.egg-info/SOURCES.txt'
    copying rocksdb/_rocksdb.cpp -> build/lib.linux-x86_64-3.6/rocksdb
    copying rocksdb/_rocksdb.pyx -> build/lib.linux-x86_64-3.6/rocksdb
    copying rocksdb/backup.pxd -> build/lib.linux-x86_64-3.6/rocksdb
    copying rocksdb/cache.pxd -> build/lib.linux-x86_64-3.6/rocksdb
    copying rocksdb/comparator.pxd -> build/lib.linux-x86_64-3.6/rocksdb
    copying rocksdb/db.pxd -> build/lib.linux-x86_64-3.6/rocksdb
    copying rocksdb/env.pxd -> build/lib.linux-x86_64-3.6/rocksdb
    copying rocksdb/filter_policy.pxd -> build/lib.linux-x86_64-3.6/rocksdb
    copying rocksdb/iterator.pxd -> build/lib.linux-x86_64-3.6/rocksdb
    copying rocksdb/logger.pxd -> build/lib.linux-x86_64-3.6/rocksdb
    copying rocksdb/memtablerep.pxd -> build/lib.linux-x86_64-3.6/rocksdb
    copying rocksdb/merge_operator.pxd -> build/lib.linux-x86_64-3.6/rocksdb
    copying rocksdb/options.pxd -> build/lib.linux-x86_64-3.6/rocksdb
    copying rocksdb/slice_.pxd -> build/lib.linux-x86_64-3.6/rocksdb
    copying rocksdb/slice_transform.pxd -> build/lib.linux-x86_64-3.6/rocksdb
    copying rocksdb/snapshot.pxd -> build/lib.linux-x86_64-3.6/rocksdb
    copying rocksdb/status.pxd -> build/lib.linux-x86_64-3.6/rocksdb
    copying rocksdb/std_memory.pxd -> build/lib.linux-x86_64-3.6/rocksdb
    copying rocksdb/table_factory.pxd -> build/lib.linux-x86_64-3.6/rocksdb
    copying rocksdb/universal_compaction.pxd -> build/lib.linux-x86_64-3.6/rocksdb
    creating build/lib.linux-x86_64-3.6/rocksdb/cpp
    copying rocksdb/cpp/comparator_wrapper.hpp -> build/lib.linux-x86_64-3.6/rocksdb/cpp
    copying rocksdb/cpp/filter_policy_wrapper.hpp -> build/lib.linux-x86_64-3.6/rocksdb/cpp
    copying rocksdb/cpp/memtable_factories.hpp -> build/lib.linux-x86_64-3.6/rocksdb/cpp
    copying rocksdb/cpp/merge_operator_wrapper.hpp -> build/lib.linux-x86_64-3.6/rocksdb/cpp
    copying rocksdb/cpp/slice_transform_wrapper.hpp -> build/lib.linux-x86_64-3.6/rocksdb/cpp
    copying rocksdb/cpp/utils.hpp -> build/lib.linux-x86_64-3.6/rocksdb/cpp
    copying rocksdb/cpp/write_batch_iter_helper.hpp -> build/lib.linux-x86_64-3.6/rocksdb/cpp
    running build_ext
    building 'rocksdb._rocksdb' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/rocksdb
    gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/opt/python/include/python3.6m -c rocksdb/_rocksdb.cpp -o build/temp.linux-x86_64-3.6/rocksdb/_rocksdb.o -std=c++11 -O3 -Wall -Wextra -Wconversion -fno-strict-aliasing
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
    rocksdb/_rocksdb.cpp:495:39: fatal error: utilities/merge_operators.h: No such file or directory
     #include "utilities/merge_operators.h"
                                           ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/local/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-vhcbg9kt/python-rocksdb/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-htioghan-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-vhcbg9kt/python-rocksdb/
```

RocksDB is installed using:

    apt-get install -y libsnappy-dev zlib1g-dev libbz2-dev libgflags-dev
	git clone https://github.com/facebook/rocksdb.git /tmp/rocksdb
	cd /tmp/rocksdb
	git checkout v5.2.1
	make shared_lib -j 2
	make install-shared INSTALL_PATH=/usr

This used to work with pyrocksdb. Is there anything I need to change to use it with python-rocksdb?

**Comment by twmht** [comment]
@bauerj 

Since `python-rocksdb` include the `$ROCKSDB_DIR/utilities` , you need to include the folder by adding
 
```
export CPLUS_INCLUDE_PATH=${CPLUS_INCLUDE_PATH}:`$ROCKSDB_DIR`
```

Please let me know if you have any problem.

thanks.

**Comment by bauerj** [comment]
What if there is no `merge_operator.h` like [in RocksDB 4.5.1-2 (Ubuntu)](http://packages.ubuntu.com/yakkety/amd64/librocksdb-dev/filelist)?

**Comment by twmht** [comment]
@bauerj 

I think the only way is to clone the repository and export the environment variable including the header files.

```
git clone https://github.com/facebook/rocksdb.git
cd rocksdb
export CPLUS_INCLUDE_PATH=${CPLUS_INCLUDE_PATH}:`pwd`
```

btw, I will try to remove this dependency in a few days.

thanks

**Comment by twmht** [comment]
@bauerj 

I update python-rocksdb to 0.6.6

now it should work with your config.

**Comment by bauerj** [comment]
Thanks! Now I get this error:

      __pyx_t_1 = ((__pyx_v_self->opts->compaction_pri == rocksdb::kOldestLargestSeqFirst) != 0);
                                                           ^
    rocksdb/_rocksdb.cpp:13621:55: error: 'kOldestSmallestSeqFirst' is not a member of 'rocksdb'
       __pyx_t_1 = ((__pyx_v_self->opts->compaction_pri == rocksdb::kOldestSmallestSeqFirst) != 0);
                                                           ^
    rocksdb/_rocksdb.cpp:13654:55: error: 'kMinOverlappingRatio' is not a member of 'rocksdb'
       __pyx_t_1 = ((__pyx_v_self->opts->compaction_pri == rocksdb::kMinOverlappingRatio) != 0);
                                                           ^
    rocksdb/_rocksdb.cpp: In function 'int __pyx_pf_7rocksdb_8_rocksdb_7Options_14compaction_pri_2__set__(__pyx_obj_7rocksdb_8_rocksdb_Options*, PyObject*)':
    rocksdb/_rocksdb.cpp:13752:42: error: 'kByCompensatedSize' is not a member of 'rocksdb'
         __pyx_v_self->opts->compaction_pri = rocksdb::kByCompensatedSize;
                                              ^
    rocksdb/_rocksdb.cpp:13786:42: error: 'kOldestLargestSeqFirst' is not a member of 'rocksdb'
         __pyx_v_self->opts->compaction_pri = rocksdb::kOldestLargestSeqFirst;
                                              ^
    rocksdb/_rocksdb.cpp:13820:42: error: 'kOldestSmallestSeqFirst' is not a member of 'rocksdb'
         __pyx_v_self->opts->compaction_pri = rocksdb::kOldestSmallestSeqFirst;
                                              ^
    rocksdb/_rocksdb.cpp:13854:42: error: 'kMinOverlappingRatio' is not a member of 'rocksdb'
         __pyx_v_self->opts->compaction_pri = rocksdb::kMinOverlappingRatio;
                                              ^
    rocksdb/_rocksdb.cpp: In function 'PyObject* __pyx_pf_7rocksdb_8_rocksdb_7Options_11compression___get__(__pyx_obj_7rocksdb_8_rocksdb_Options*)':
    rocksdb/_rocksdb.cpp:14139:10: error: 'kXpressCompression' is not a member of 'rocksdb'
         case rocksdb::kXpressCompression:
              ^
    rocksdb/_rocksdb.cpp:14171:10: error: 'kZSTD' is not a member of 'rocksdb'
         case rocksdb::kZSTD:
              ^
    rocksdb/_rocksdb.cpp:14235:10: error: 'kDisableCompressionOption' is not a member of 'rocksdb'
         case rocksdb::kDisableCompressionOption:
              ^
    rocksdb/_rocksdb.cpp: In function 'int __pyx_pf_7rocksdb_8_rocksdb_7Options_11compression_2__set__(__pyx_obj_7rocksdb_8_rocksdb_Options*, PyObject*)':
    rocksdb/_rocksdb.cpp:14562:39: error: 'kZSTD' is not a member of 'rocksdb'
         __pyx_v_self->opts->compression = rocksdb::kZSTD;
                                           ^
    rocksdb/_rocksdb.cpp:14630:39: error: 'kDisableCompressionOption' is not a member of 'rocksdb'
         __pyx_v_self->opts->compression = rocksdb::kDisableCompressionOption;
                                           ^
    rocksdb/_rocksdb.cpp: In function 'int __pyx_pf_7rocksdb_8_rocksdb_7Options_30max_bytes_for_level_multiplier_2__set__(__pyx_obj_7rocksdb_8_rocksdb_Options*, PyObject*)':
    rocksdb/_rocksdb.cpp:15710:54: warning: conversion to 'int' from 'double' may alter its value [-Wfloat-conversion]
       __pyx_v_self->opts->max_bytes_for_level_multiplier = __pyx_t_1;
                                                          ^
    rocksdb/_rocksdb.cpp: In function 'PyObject* __pyx_f_7rocksdb_8_rocksdb_12BaseIterator_seek_for_prev(__pyx_obj_7rocksdb_8_rocksdb_BaseIterator*, PyObject*, int)':
    rocksdb/_rocksdb.cpp:28743:30: error: 'class rocksdb::Iterator' has no member named 'SeekForPrev'
               __pyx_v_self->ptr->SeekForPrev(__pyx_v_c_key);
                                  ^
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by twmht** [comment]
@bauerj 

It seems your `rocksdb` is not up to date, what is the version of your `rocksdb`?

**Comment by bauerj** [comment]
Sorry for the late response. This is with `v4.5.1`.

**Comment by twmht** [comment]
@bauerj 

Please use with the latest rocksdb.

**Comment by bauerj** [comment]
So rocksdb 5.2.1 is a requirement to use python-rocksdb? If so, you should add that to the README.

**Comment by twmht** [comment]
@bauerj 

ok, I can add it into README.

thanks!

**Comment by twmht** [comment]
now `python-rocksdb` can support the latest rocksdb.
