### ISSUE TITLE
Will python-rocksdb 1.0 support bytes?

### ISSUE THREAD

**Issue by zjkmxy** [twmht/python-rocksdb#53]
Hello. I have tried your pybind11 branch and found that new Blob class only supports string.
Therefore, when I try to put a binary file and get it, Python 3.6 will raise an encoding exception.
I wonder if you still want to support bytes?

**Comment by iFA88** [comment]
Hi. I think the standard input for keys and values are `bytes`. I'm using the `master` branch of `python-rocksdb`.

**Comment by zjkmxy** [comment]
Thank you for your reply. I know the `master` branch is using `bytes`. But it seems that they want to switch to the experimental branch, `pybind11`, in the future.
I'm asking for that one.

**Comment by iFA88** [comment]
I have checked the `pybind11`.. Well, that's definitely wrong, keys and values must be `bytes` for python3 and for python2 `str`.

**Comment by twmht** [comment]
Yup. pybind11 branch does not support bytes yet.  But it should support that soon.

**Comment by zjkmxy** [comment]
That's great. Thanks!

**Comment by twmht** [comment]
@zjkmxy 

Now it supports bytes now. BTW, it's an experimental branch since a lot of features are not migrated yet. But the migration should be soon.
