### ISSUE TITLE
install problems in mac os

### ISSUE THREAD

**Issue by runrunliuliu** [twmht/python-rocksdb#6]
Hi,

I have tried to install python-rocksdb on mac os. Here is the steps:

1. brew install rocksdb
2. pip install python-rocksdb

After then, python -c 'import rocksdb'

Symbol not found: __ZNK7rocksdb13MergeOperator17PartialMergeMultiERKNS_5SliceERKSt5dequeIS1_SaIS1_EEPSsPNS_6LoggerE
  Referenced from: /Users/liu/Library/Caches/Python-Eggs/python_rocksdb-0.6.6-py2.7-macosx-10.7-x86_64.egg-tmp/rocksdb/_rocksdb.so
  Expected in: flat namespace

I also try to install from source code of python-rocksdb, however , the same problems apprear.

So, Is there any instructions for install python-rocksdb on mac os? Thx

**Comment by runrunliuliu** [comment]
By the way,


After do 'pip install python-rocksdb',  
 otool -L /Users/liu/anaconda2/lib/python2.7/site-packages/rocksdb/_rocksdb.so

/Users/liu/anaconda2/lib/python2.7/site-packages/rocksdb/_rocksdb.so:
	**/usr/local/opt/rocksdb/lib/librocksdb.5.4.dylib** (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/snappy/lib/libsnappy.1.dylib (compatibility version 5.0.0, current version 5.1.0)
	/usr/lib/libbz2.1.0.dylib (compatibility version 1.0.0, current version 1.0.5)
	libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
	/usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 104.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
	/usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 283.0.0)

**Comment by twmht** [comment]
this is interesting.

i don't have mac os, but I think this problem is related with https://stackoverflow.com/questions/35006614/what-does-symbol-not-found-expected-in-flat-namespace-actually-mean


How do you compile rocksdb?

**Comment by EliFinkelshteyn** [comment]
Extra data point here: I'm on OS X 10.11.6 (El Capitan) using RocksDB 5.4.6 and it worked fine for me. Just:

1. brew install rocksdb
2. pip install python-rocksdb

**Comment by VenkataKarthikP** [comment]
which version of python did you use ?

**Comment by twmht** [comment]
this problem can be solved by `python-rocksdb` 0.6.9

**Comment by yihuang** [comment]
I still have this problem with the most recent version on pypi with mac Mojave, but it's ok with git master version.
