### ISSUE TITLE
No support for 5.4.6?

### ISSUE THREAD

**Issue by EliFinkelshteyn** [twmht/python-rocksdb#8]
Installing the latest version of rocksdb (5.4.6) and attempting to use python-rocksdb, I get:

```
ImportError: dlopen(/Users/Eli/.virtualenvs/ac/lib/python2.7/site-packages/rocksdb/_rocksdb.so, 2): Library not loaded: /usr/local/opt/rocksdb/lib/librocksdb.5.3.dylib
  Referenced from: /Users/Eli/.virtualenvs/ac/lib/python2.7/site-packages/rocksdb/_rocksdb.so
  Reason: image not found
```

Is this somehow pegged to 5.3?

**Comment by twmht** [comment]
@EliFinkelshteyn 

I have tested rocksdb 5.4.6, and everything is fine.

You can try my test steps

```
git clone https://github.com/facebook/rocksdb.git
git checkout 5.4.6
mkdir build
cd build
cmake ..
make -j 12
export CPLUS_INCLUDE_PATH=${CPLUS_INCLUDE_PATH}:$HOME/rocksdb/include
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:$HOME/rocksdb/build
export LIBRARY_PATH=${LIBRARY_PATH}:$HOME/rocksdb/build

pip install python-rocksdb
python -c 'import rocksdb'
```

**Comment by EliFinkelshteyn** [comment]
It looks like if you've installed under a previous version or rocksdb, the old dependencies get cached. For anyone having this issue in the future, you have to reinstall without using cache:

`pip install --no-cache-dir python-rocksdb`
